[package]
name = "file_sparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "5.1.4"
indicatif = "0.17.8"
structopt = "0.3.26"
